# OrangeFox Settings 
OF_HIDE_NOTCH :- 0
OF_ALLOW_DISABLE_NAVBAR :- 0

# GUI related
OF_SCREEN_H :- 2400
OF_STATUS_H :- 42
OF_STATUS_INDENT_LEFT :- 50
OF_STATUS_INDENT_RIGHT :- 50
OF_CLOCK_POS :- 1

# Miscellaneous
OF_SPLASH_MAX_SIZE :- 4096
